# Generated by Django 2.2.4 on 2019-09-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user_name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_kakao_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
