# Generated by Django 2.2.4 on 2019-09-03 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190903_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='user_kakao_id',
            new_name='social_login_id',
        ),
    ]
