# Generated by Django 2.2.4 on 2019-08-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='content',
        ),
    ]
