# Generated by Django 2.2.4 on 2019-08-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20190829_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='deleted_at',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
