# Generated by Django 2.2.4 on 2019-08-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_auto_20190830_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='deleted_at',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
