# Generated by Django 2.2.4 on 2019-08-30 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_auto_20190830_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='deleted_at',
            new_name='deleted',
        ),
    ]
