# Generated by Django 2.2.4 on 2019-08-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0014_auto_20190830_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
