# Generated by Django 2.2.4 on 2019-08-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0015_auto_20190830_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
