# Generated by Django 2.2.4 on 2019-09-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0016_auto_20190830_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='deleted',
            new_name='delete',
        ),
    ]
