# Generated by Django 2.2.4 on 2019-09-02 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20190901_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='deleted_at',
            new_name='deleted',
        ),
    ]
