# Generated by Django 2.2.4 on 2019-09-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20190902_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.AddField(
            model_name='menu',
            name='mene_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
