# Generated by Django 2.2.4 on 2019-09-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20190904_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='mene_name',
            new_name='menu_name',
        ),
    ]
